### ISSUE TITLE
Selector returns wrong DOM node if component doesn't render a real DOM elements

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-vue-selectors#20]
Markup for reproduce:
```js
<html>
    <head>
		<script src="vue.js"></script>
	</head>
	<body>
	    <div id='root'>
			<App></App>
		</div>
		<script>
		   Vue.component('total-value', {  
		       props: ['formatProperty'],
		       template: '<div>{{ formatProperty }}</div>' 
		   });
		   Vue.component('Hello', { template: '<total-value formatProperty="%d"></total-value>' });
		   Vue.component('App', { template: '<Hello></Hello>' });
		   
		   new Vue({ el: '#root' });
		</script>
	</body>
</html>
```

Test for reproduce:
```js
import VueSelector from "testcafe-vue-selectors";

fixture `https://stackoverflow.com/questions/44585727/testcafe-vue-selectors-cant-grab-vue-component`
    .page('http://localhost:8080');

test('test', async t => {
    const totalValue = VueSelector("total-value");

    await t.expect(totalValue.getVue(({ props }) => props.formatProperty)).eql('%d');
});
```

**Comment by blainehansen** [comment]
It seems to me that it might be a good idea to just directly use some of the [`vue-devtools`](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L136) methods to do the work of finding nodes. I'm comparing their code to this plugin's and it seems that could be causing some of these problems.

**Comment by blainehansen** [comment]
I feel that I could help in solving some of these bugs, but you'll have to help me understand how to work with and debug a testcafe plugin.

I've copied the `index.js` of this plugin to my directory, and tried to 
 and I've been trying to debug this plugin, but it seems that my `console.log` calls and other attempts

```js
}).addCustomMethods({
	getVue: (node, fn) => {
		console.log(node)
```

```js
import { Selector } from 'testcafe'
// import VueSelector from 'testcafe-vue-selectors'
import VueSelector from './plugin'
```

**Comment by blainehansen** [comment]
And my attempt at using the node debugger didn't work:

`node inspect ./node_modules/testcafe -- 'chrome:headless' test/end-to-end/*.spec.js --app 'npm run dev' --app-init-delay 12000`

I would love to help solve these problems. It's hard to work with a black box though ha.
