### ISSUE TITLE
Selector should wait for component loading

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-vue-selectors#26]
see https://testcafe-discuss.devexpress.com/t/testcafe-for-nuxt-apps-vue-ssr-library/457

**Comment by SayedShahidi** [comment]
@miherlosev Having the same issues. I have increased the timeouts to prevent random `Cannot read property '__vue__' of undefined` messages, even though they are loaded.

**Comment by RaviH** [comment]
Hi @SayedShahidi , how did you set/increase the timeouts, please?
