### ISSUE TITLE
Add note about running in development mode

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-vue-selectors#28]
VueSelector will work only if the Vue.js application was built in the development mode.
In the production mode, it is impossible to retrieve information about components (behavior like in the vue-devtools extension).

**Comment by dasDaniel** [comment]
yes, the readme should certainly mention that. Not wait until the following error occurs

```
   1) An error occurred in getVue code:

      TypeError: Cannot read property '__vue__' of undefined
```

**Comment by miherlosev** [comment]
Also I will add a more clear message.
Something like this: 
`The page doesn\'t contain Vue components or your Vue app is not in a development mode`.

**Comment by TheRaven** [comment]
My app is running using the following command:
`cross-env NODE_ENV=development webpack-dev-server --open --hot`

but I still get 
```
1) An error occurred in getVue code:

      TypeError: Cannot read property '__vue__' of undefined
```

Any pointers?
