### ISSUE TITLE
Errors on passing to component some variables with specific names like value or data

### ISSUE THREAD

**Issue by Ranmus** [DevExpress/testcafe-vue-selectors#29]
Test case scenario:
There are two components: A and B. A is parent of B and A is passing to B  variable "value" via prop named "message" like this:
`<component-b :message="value"></component-b>`

Value is defined in data section of component A. When testcafe tests this structure it constantly throws errors to client console:

> Property of method "nodeName" (or "nodeType") is not defined on the instance but referenced during render...

When variable is not called like "value" or "data" (these names are not reserved keywords in Vue) then errors are not throwed.

To reproduce these errors, download my spa template (testcafe-error branch):
```
git clone https://github.com/Ranmus/vue-spa-template.git
cd vue-spa-template
git checkout testcafe-error
yarn
npm run tests:functional
```
I've added 60 seconds to wait until test is passed. During this time check client console.

**Comment by AlexanderMoskovkin** [comment]
Hi @Ranmus,

Thanks for your detailed report. The problem relates to the `testcafe` but not to `testcafe-vue-selectors`. I've reproduced the issue with a simple example (see https://github.com/DevExpress/testcafe/issues/1895).

So, I close this in favor of https://github.com/DevExpress/testcafe/issues/1895. Please subscribe on it to be notified about our progress.

**Comment by Ranmus** [comment]
Thanks for fast response!
