### ISSUE TITLE
Can not select <router-view> component

### ISSUE THREAD

**Issue by jkirkby91-2** [DevExpress/testcafe-vue-selectors#30]
I'm trying to test certain parts of my applications computed properties such as locale or form validation results which are contained on the component loaded into the `<router-view>` component

You can see in the screenshot

https://imgur.com/PswNqQi/

my default route view loads up my welcome component, using VueSelector() how do I actually select this component to access the state/prop/ computed data.

If i do 

>   const root = VueSelector()
>   const rootVue = await root.getVue()

This selects the `<QLayout>` component

If I do 

>   const welcome = VueSelector('welcome')
>   const welcomeVue = await welcome.getVue()

I get a 

> node.__vue__ undefined

I've tried passing all sorts of combinations into VueSelector like

> VueSelector('q-layout welcome')
> VueSelector('router-view')
> VueSelector('q-layout router-view')
> VueSelector('router-view welcome')

None of which actually select the component served from the route. I can however select any component nested within welcome such as the Login component like

>   const login = VueSelector('login')
>   const loginVue = await login.getVue()
> 
>
>   await t
>     .expect(loginVue.computed.isAuthenticated).eql(false)
>     .expect(loginVue.props.facebook).eql(true)

Any help is really appreciated because otherwise I can't test alot of data on any components server from the router

**Comment by miherlosev** [comment]
Hi @jkirkby91-2 
 
The code
```js
const welcome = VueSelector('welcome')
const welcomeVue = await welcome.getVue()
```
should work.
 
It looks like you specified a wrong component tag name.
Could you please provide code with the `Welcome` component definition?
Something like this:
```js
Vue.component('list-item', {
props: ['id'],
template: '<li :id="id"><p>{{ id }}</p></li>'
});
```

**Comment by jkirkby91-2** [comment]
The welcome component is served from vue-router so I will give an excerpt of my router/index.js

```
import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

/**
 * @param component
 * @returns {function()}
 */
function load (component) {
  return () => import(`@/${component}.vue`)
}

/**
 * @type {VueRouter}
 */
const router = new VueRouter({

  base: '/',
  hashbang: false,

  routes: [
    {
      path: '/',
      component: load('Welcome'),
      meta: {
        requiresAuth: false
      }
    }
}
```

An excerpt of my App.vue html template looks like this

```
<template>
  <q-layout ref="layout" @scroll="scrollHandler">
    <div id="q-app" :class="this.$router.currentRoute.name">
      <div class="container scroll" style="height: 80vh; overflow: scroll">
        <div class="row justify-center">
          <transition name="slide-fade">
            <router-view></router-view>
          </transition>
        </div>
        <q-scroll-observable @scroll="scrollHandler" />
      </div>
    </div>
</q-layout>
```

vue-router I guess "injects" the welcome component into the  `<router-view></router-view>`

Here is an example test trying to grab the welcome component

```
import VueSelector from 'testcafe-vue-selectors'
import { Selector, ClientFunction } from 'testcafe'

const setFakeVue = ClientFunction(() => {
  window.Vue = { version: "2.2.6" }
})

fixture(`test welcome component`)
  .beforeEach(async t => {
    await setFakeVue()
  })
  .page('http://localhost:8080')

test('can we select the welcome component', async testController => {
  const welcome = VueSelector('welcome')
  const welcomeVue = await welcome.getVue()

  console.log(welcomeVue)

  const welcome1 = VueSelector('Welcome')
  const welcomeVue1 = await welcome1.getVue()

  console.log(welcomeVue1)
})
```

Which isn't having any of it.

**Comment by miherlosev** [comment]
Unfortunately, at present `testcafe-vue-selectors` does not support components loaded via `vue-router`.
I've create the [issue](https://github.com/DevExpress/testcafe-vue-selectors/issues/31) on this.

As a workaround, try to use the build-in [TestCafe selectors](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html).

**Comment by jkirkby91-2** [comment]
is there a way to access vue computed properties with the default selectors?

**Comment by miherlosev** [comment]
Yes.
I've created an example
```js
import { Selector, ClientFunction } from 'testcafe';

fixture `Vue properties`
	.page('http://localhost:8080/test/data/');
	
test('get Vue specific properties', async t => {
	const node = Selector('#app');
	
    const getVueProperties = ClientFunction(() => {
		function getData (instance, prop) {
            const result = {};

            Object.keys(prop).forEach(key => {
                result[key] = instance[key];
            });


            return result;
        }
		
		 function getProps (instance) {
            return getData(instance, instance.$options.props || {});
        }

        function getState (instance) {
            const props   = instance._props || instance.$options.props;
            const getters = instance.$options.vuex && instance.$options.vuex.getters;
            const result  = {};

            Object.keys(instance._data)
                .filter(key => !(props && key in props) && !(getters && key in getters))
                .forEach(key => {
                    result[key] = instance._data[key];
                });

            return result;
        }

        function getComputed (instance) {
            return getData(instance, instance.$options.computed || {});
        }
		
		var nodeVue = node().__vue__;
		
		if (!nodeVue)
            return null;
		
		var props    = getProps(nodeVue);
        var state    = getState(nodeVue);
        var computed = getComputed(nodeVue);
		
		return {
			props: props,
			state: state,
			computed: computed
		};
	}, { dependencies: { node } });	
	
	const vueProperties = await getVueProperties();
	
	console.log(vueProperties);
});	
```
