### ISSUE TITLE
 Support component loaded via vue-router

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-vue-selectors#31]
https://github.com/vuejs/vue-router

see question https://github.com/DevExpress/testcafe-vue-selectors/issues/30

**Comment by miherlosev** [comment]
NOTE: need to check user case from https://github.com/DevExpress/testcafe-vue-selectors/issues/30

**Comment by blainehansen** [comment]
A fix for this would be much appreciated. Thanks for the good work!

**Comment by Thejaswi05** [comment]
It would be great to add this enhancement.. Our application is loaded via vue router.

**Comment by Zebirdman** [comment]
this would be a massive help, thankyou
