### ISSUE TITLE
Vue cmp state doens't seem to update

### ISSUE THREAD

**Issue by idmick** [DevExpress/testcafe-vue-selectors#37]
I'm trying to perform an action (delete a contact) while my the length contacts array is bigger than 0. But it seems that the state doesn't change after I deleted a contact.

The console log shows that the contact array length remains at one even though I delete a contact.

Am I doing something wrong or is there a way to my the state of my vue cmp reactive in TestCafe?

Thnx

```
const adviceAnalysisVueCmpState = await advicePage.step1.adviceAnalysis.getVue()
while (adviceAnalysisVueCmpState.computed.contacts.length > 0) {
    await t
    .click(advicePage.step1.deleteContact)
    .click(advicePage.step1.deleteFromAdvice)
    console.log(adviceAnalysisVueCmpState.computed.contacts.length, 2)
  }
```

**Comment by miherlosev** [comment]
Hi @idmick

The `getVue` method returns the component state at the current moment. After the state was retrieved, it will not track changes.
You need to rewrite your code as folows:
```js
let adviceAnalysisVueCmpState = await advicePage.step1.adviceAnalysis.getVue();
while (adviceAnalysisVueCmpState.computed.contacts.length > 0) {
    await t
    .click(advicePage.step1.deleteContact)
    .click(advicePage.step1.deleteFromAdvice)
    console.log(adviceAnalysisVueCmpState.computed.contacts.length, 2);

adviceAnalysisVueCmpState = await advicePage.step1.adviceAnalysis.getVue();
  }
```
