### ISSUE TITLE
Return ref along with data, props, computed and state on getVue()

### ISSUE THREAD

**Issue by ChandruCR** [DevExpress/testcafe-vue-selectors#40]
It would be really helpful 
if we can get the ref of the component on getVue 
or 
if we can pass ref in VueSelector and get the component matching the ref(similar to vue test utils used for unit testing).

I can develop this feature and raise a pull request.

**Comment by miherlosev** [comment]
It would be great.

**Comment by ChandruCR** [comment]
@miherlosev 
I have made the changes and raised a pull request. 
Preliminary checks have passed.
Please review and merge.
