### ISSUE TITLE
Can't get access to global Vue (Nuxt) object, fails with error.

### ISSUE THREAD

**Issue by souljorje** [DevExpress/testcafe-vue-selectors#43]
Hi!
I'm trying to get access to root Vue (Nuxt) instance, but I can't:
```js
const nuxt = await VueSelector();
const vm = await nuxt.getVue();
console.log(vm);
```
it fails with error: 
```
1) getVue cannot return DOM elements. Use Selector functions for this purpose.
```

But recently, when I tried to use it with testcafe@0.22.0 it worked well, I could get root Vue (Nuxt) instance and read properties.

No matter if I use testcafe-vue-selectors or https://github.com/kartojal/testcafe-nuxt-selectors it fails in same way. Tried to dive deeper to TestCafe code, but didn't succeed.

Here's repo with reproduction instructions:
https://github.com/souljorje/TestCafe-nuxt-issue

Hope for your help! 
Cheerz, Georgiy 🙌

**Comment by Farfurix** [comment]
@souljorje 

Hello,

Thank you for the repository.

I've reproduced this issue under Windows 10 / Chrome 74 / `testcafe@1.1.4` / `testcafe-nuxt-selectors` / `testcafe-vue-selectors`. Our team will research it and check for a suitable solution.
