### ISSUE TITLE
Basic usage- Vue render content not available

### ISSUE THREAD

**Issue by yarnball** [DevExpress/testcafe-vue-selectors#45]
Hi there,

I may be missing something obvious- but I have not been able to "find" any Vue components, aside from the initial wrapper.

For example:

In /main.js I'm importing "App" (which itself imports many components).

```
import Vue from "vue";
import App from "./App.vue";
...
new Vue({
  router,
  render: h => h(App),
  data:{
  	testing:1234
  }
}).$mount("#app");
```

When I run:
```
const rootVue = VueSelector();
const test= await rootVue.getVue();
console.log(test)
```
It logs:
```
{ props: {},
  state: { testing: 1234 },
  computed: {},
  ref: undefined }
```

However, if I try to specify anything else (such as `app` or any other components)- it tells me - 
```
Cannot read property '__vue__' of undefined
```

For reference, this is what the vue developer tools show me:
![Screen Shot 2019-07-15 at 4 53 30 pm](https://user-images.githubusercontent.com/13043067/61199403-27807480-a721-11e9-8cdc-1f8dbeb90d3d.jpg)

Could you please clarify how this is to be used?

**Comment by VasilyStrelyaev** [comment]
This error indicates that TestCafe was unable to find the specified component. To help us determine if it is a TestCafe bug or the component does not exist, please provide a link to the application you are testing and the exact selectors that cause this error.
 
Note that the `VueSelector` method takes the component name as a parameter. However, depending on how you add components to the page, the actual name may match the one you see in the Developer Tools or not. You can examine the application code to see under what names the components are actually added. Alternatively, you can simply try different variations (like `RouterLink`, `router-link`, etc.).

**Comment by yarnball** [comment]
Thanks. I didn't have any success accessing any of the selectors, and tried variations such as  RouterLink, router-link, hello-world etc.

My code- this is just "out of the box" from the vue CLI (eg here: https://codesandbox.io/s/vue-template-6y3g5)

**Comment by miherlosev** [comment]
Hi @yarnball 

Thank you for the provided example. I've reproduced the problem.
