### ISSUE TITLE
Unable to find a Vue componant within a named slot

### ISSUE THREAD

**Issue by cnouguier** [DevExpress/testcafe-vue-selectors#46]
Given the following template:

```
<template>
  <k-page padding>
    <template v-slot:page-content>
        <k-grid ref="membersGrid" service="members" :renderer="renderer" :contextId="contextId" :base-query="baseQuery" :filter-query="searchQuery" />
    </template>
  </k-page>
</template>
```

`const pageVue= await VueSelector('k-page').getVue()`  works
`const membersVue= await VueSelector('k-grid').getVue()` doesnt' work and returns: `getVue cannot return DOM elements. Use Selector functions for this purpose`

Tested with:

- TestCafe 1.8.5
- testcafe-vue-selectors 3.1.0
- vue 2.6.10

**Comment by SergeyShurygin** [comment]
Hi Christophe,

I did not manage to reproduce it. Please refer to my sample project in the attachment. Would you please modify it or send us your project where we can see this issue?

[vue-test.zip](https://github.com/DevExpress/testcafe-vue-selectors/files/4662467/vue-test.zip)
My test code:

import VueSelector from 'testcafe-vue-selectors';
fixture(' vue named slot test')
    .page('http://localhost:8080/');

test('My first test', async t => {
    const pageVue= await VueSelector('PageTemplate').getVue();
    const membersVue= await VueSelector('HelloWorld').getVue();
    await t.expect(membersVue.props.msg).eql('Welcome to Your Vue.js + TypeScript App');
});

**Comment by cnouguier** [comment]
Hi Sergey,
Thanks for your reply.  I need to investigate. We are using async dynamic components: https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components. Do you think it is a possible explanation ?

**Comment by aleks-pro** [comment]
Hello @cnouguier ,

> Do you think it is a possible explanation ?

To give you a precise answer, we need to check a simple working example in which we can reproduce the problem.

**Comment by cnouguier** [comment]
Hi,
Sorry for my late reply. I tested and it works with async dynamic components. 
Don't know what happens on my case. For now I suggest to close the issue.
