### ISSUE TITLE
How to get to deeply nested component?

### ISSUE THREAD

**Issue by RaviH** [DevExpress/testcafe-vue-selectors#48]
How do I get to TaskList component? Do I need to provide all the elements from all the way from Root onto TaskList?

`const listItem = VueSelector('Root App Layout QLayout QPageContainer TodoPage QPage TaskList');`

Is their a good tutorial / video on a deep tree like that? The problem is I am using Quasar and so I don't have complete control on how deep the tree gets.

![image](https://user-images.githubusercontent.com/141136/87734511-ab7f9900-c787-11ea-95a3-433df5bef8c8.png)

It would be great if I could get to TaskList simply by specifying: 

`const listItem = VueSelector('TaskList');`

**Comment by Dmitry-Ostashev** [comment]
There is no necessity to specify the whole components hierarchy. The short like selector `VueSelector('TaskList')` should work. You may combine it with [filter functions](http://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#functional-style-selectors).
