### ISSUE TITLE
.getVue() causes error

### ISSUE THREAD

**Issue by ngthuongdoan** [DevExpress/testcafe-vue-selectors#56]
Hi,

I want to get component props but get this messy error. I've already followed the instruction. Still don't know where it came from.

![image](https://user-images.githubusercontent.com/45509523/125234096-2aab9c80-e30a-11eb-87bc-5403f455c51e.png)

```vue
<script>
// BarChart.vue
import { Bar } from 'vue-chartjs';
export default {
  extends: Bar,
  props: ['chartData'],
  data() {
    return {
      options: {},
    }
  },
  watch: {
    chartData: {
      deep: true,
      handler() {
        this.renderChart(this.chartData, this.options);
      },
    },
  },
  mounted() {
    this.renderChart(this.data, this.options);
  },
};
</script>

```
```js
// Test file
  const Chart = await VueSelector('BarChart');
  const response = await fetchData(
    COUNTRIES.find((c) => c.name === 'Viet Nam')
  );
  try {
    const chartData = await Chart.getVue(({ props }) => props.chartData);
    await controller.expect(Chart.exists).ok();
    await controller.expect(chartData).eql(response);
  } catch (e) {
    console.error(e);
  }
```

**Comment by pavsenin** [comment]
Hello,
Thank you for providing code samples, but they aren't enough to reproduce the issue on my side.
Would you please check whether the 'await' operator is needed in the following lines?
`const Chart = await VueSelector('BarChart');`
`const chartData = await Chart.getVue(() => props.chartData);`
Change your code to
`const Chart = VueSelector('BarChart');
const response = await fetchData(
COUNTRIES.find((c) => c.name === 'Viet Nam')
);
try ) => props.chartData);
await controller.expect(Chart.exists).ok();
await controller.expect(chartData).eql(response);
} catch (e) {
console.error(e);
}`
and try to reproduce issue.
If this does not help, please send me the full example where it is reproduced.

**Comment by ngthuongdoan** [comment]
Sorry, I'm too busy this time.
When I tried the code above, it threw me this error. Still don't know what is it?
![image](https://user-images.githubusercontent.com/45509523/126869062-83cd4ab3-722b-40ba-ac15-81bb63b310e4.png)

**Comment by Dmitry-Ostashev** [comment]
I was trying to reproduce the error with the `vue-chartjs` demo: https://codesandbox.io/s/vue-chartjs-demo-forked-58sxc?file=/src/App.vue.  I have gotten the following error:

`getVue cannot return DOM elements. Use Selector functions for this purpose.`

Could you please run your test without the `try ... catch` block to make sure that the issue is caused by the same error?
