### ISSUE TITLE
Vue3 compatibility

### ISSUE THREAD

**Issue by Gastienne** [DevExpress/testcafe-vue-selectors#59]
Hello, is there a plan for vue3 compatibility?

**Comment by VasilyStrelyaev** [comment]
Thank you for your inquiry.

At present, we do not have Vue3 support on our roadmap as we didn't receive any requests regarding Vue3 yet. I will mark this issue as a suggestion, and we will take it into account during our future planning.

**Comment by phil-w** [comment]
Oh. Yeah, Vue 3 would be handy. And Yarn2 if you're feeling modern.
